/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 8c1b540238caa03372d4af1558caba1d)
interface __BaseEnv_Env {
	FD_CLAIMS_USERS: KVNamespace;
	FD_LIGHT_STATE: KVNamespace;
	FD_AI_CACHE: KVNamespace;
	FD_PROJECT_FILES: R2Bucket;
	FD_CLAIMS_DB: D1Database;
	GOOGLE_CLIENT_ID: string;
	ANTHROPIC_API_KEY: string;
	AUTH_SECRET: string;
	GMAIL_WEBHOOK_SECRET: string;
	RESEND_API_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_CLIENT_ID" | "ANTHROPIC_API_KEY" | "AUTH_SECRET" | "GMAIL_WEBHOOK_SECRET" | "RESEND_API_KEY">> {}
}
