/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: e663b6adbe0fcd8ed18286ddfde878a5)
interface __BaseEnv_Env {
	FD_CLAIMS_USERS: KVNamespace;
	FD_LIGHT_STATE: KVNamespace;
	FD_AI_CACHE: KVNamespace;
	FD_PROJECT_FILES: R2Bucket;
	FD_CLAIMS_DB: D1Database;
	GOOGLE_CLIENT_ID: string;
	NOTION_API_KEY: string;
	NOTION_DATABASE_ID: string;
	PORT: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_CLIENT_ID" | "NOTION_API_KEY" | "NOTION_DATABASE_ID" | "PORT">> {}
}
