/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 701e2a3d792d7c8bb8a310082fb27c74)
interface __BaseEnv_Env {
	FD_CLAIMS_USERS: KVNamespace;
	FD_LIGHT_STATE: KVNamespace;
	FD_AI_CACHE: KVNamespace;
	FD_PROJECT_FILES: R2Bucket;
	FD_CLAIMS_DB: D1Database;
	GOOGLE_CLIENT_ID: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_CLIENT_ID">> {}
}
